// Code generated by go generate; DO NOT EDIT.
// Embedded Kubernetes OpenAPI schemas for offline validation

package embeddedschemas

import (
	"embed"
	"encoding/json"
	"strings"
)

//go:embed swagger_*.json
var schemasFS embed.FS

// BuiltInTypesByK8sVersion maps Kubernetes versions to their OpenAPI definitions (extracted at runtime)
var BuiltInTypesByK8sVersion map[string][]byte

// ScopesByK8sVersion maps Kubernetes versions to GVK → scope mappings (extracted at runtime)
var ScopesByK8sVersion map[string]map[string]string

// ResourceNamesByK8sVersion maps Kubernetes versions to GVK → plural resource name (extracted at runtime)
var ResourceNamesByK8sVersion map[string]map[string]string

func init() {
	BuiltInTypesByK8sVersion = make(map[string][]byte)
	ScopesByK8sVersion = make(map[string]map[string]string)
	ResourceNamesByK8sVersion = make(map[string]map[string]string)

	entries, err := schemasFS.ReadDir(".")
	if err != nil {
		panic("reading embedded schemas: " + err.Error())
	}

	for _, entry := range entries {
		if entry.IsDir() || !strings.HasPrefix(entry.Name(), "swagger_") {
			continue
		}

		// Extract version from filename: swagger_v1.30.json -> v1.30
		version := strings.TrimPrefix(entry.Name(), "swagger_")
		version = strings.TrimSuffix(version, ".json")

		data, err := schemasFS.ReadFile(entry.Name())
		if err != nil {
			panic("reading " + entry.Name() + ": " + err.Error())
		}

		// Parse swagger to extract definitions and scopes
		var swagger struct {
			Definitions map[string]json.RawMessage `json:"definitions"`
			Paths       map[string]struct {
				Get *struct {
					GVK *struct {
						Group   string `json:"group"`
						Version string `json:"version"`
						Kind    string `json:"kind"`
					} `json:"x-kubernetes-group-version-kind"`
				} `json:"get"`
			} `json:"paths"`
		}

		if err := json.Unmarshal(data, &swagger); err != nil {
			panic("unmarshaling " + entry.Name() + ": " + err.Error())
		}

		// Store definitions as JSON
		definitionsJSON, err := json.Marshal(swagger.Definitions)
		if err != nil {
			panic("marshaling definitions for " + version + ": " + err.Error())
		}
		BuiltInTypesByK8sVersion[version] = definitionsJSON

		// Extract scope info and resource names from paths
		scopes := make(map[string]string)
		resourceNames := make(map[string]string)
		for path, pathItem := range swagger.Paths {
			if pathItem.Get == nil || pathItem.Get.GVK == nil {
				continue
			}

			gvk := pathItem.Get.GVK
			key := gvk.Group + "/" + gvk.Version + "/" + gvk.Kind

			// Namespaced resources have paths like: /api/v1/namespaces/{namespace}/pods
			// Cluster-scoped resources have paths like: /api/v1/nodes
			// Extract resource name from the path
			isNamespaced := strings.Contains(path, "/namespaces/{namespace}/")

			// Parse resource name from path
			// /api/v1/pods → "pods"
			// /apis/apps/v1/deployments → "deployments"
			// /api/v1/namespaces/{namespace}/pods → "pods"
			parts := strings.Split(path, "/")
			var resourceName string
			for i := len(parts) - 1; i >= 0; i-- {
				if !strings.HasPrefix(parts[i], "{") && parts[i] != "" {
					resourceName = parts[i]
					break
				}
			}

			// If we already saw this resource and it was namespaced, keep that
			if existing, ok := scopes[key]; ok && existing == "Namespaced" {
				continue
			}

			if isNamespaced {
				scopes[key] = "Namespaced"
			} else {
				scopes[key] = "Cluster"
			}

			if resourceName != "" {
				resourceNames[key] = resourceName
			}
		}

		ScopesByK8sVersion[version] = scopes
		ResourceNamesByK8sVersion[version] = resourceNames
	}
}
