#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd ${REPO_ROOT}/website

# Install dependencies
npm ci

# Run tests
npm test

# Type check
npm run typecheck

# Build the site
npm run build
