#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd ${REPO_ROOT}

# Build
go build cmd

# we currently cannot run e2e tests without kind available
echo "E2E tests are currently skipped"
# make test-e2e-kind
