//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/kubernetes-sigs/kro/api/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphRevision) DeepCopyInto(out *GraphRevision) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphRevision.
func (in *GraphRevision) DeepCopy() *GraphRevision {
	if in == nil {
		return nil
	}
	out := new(GraphRevision)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GraphRevision) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphRevisionList) DeepCopyInto(out *GraphRevisionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GraphRevision, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphRevisionList.
func (in *GraphRevisionList) DeepCopy() *GraphRevisionList {
	if in == nil {
		return nil
	}
	out := new(GraphRevisionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GraphRevisionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphRevisionSpec) DeepCopyInto(out *GraphRevisionSpec) {
	*out = *in
	in.DefinitionSpec.DeepCopyInto(&out.DefinitionSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphRevisionSpec.
func (in *GraphRevisionSpec) DeepCopy() *GraphRevisionSpec {
	if in == nil {
		return nil
	}
	out := new(GraphRevisionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphRevisionStatus) DeepCopyInto(out *GraphRevisionStatus) {
	*out = *in
	if in.TopologicalOrder != nil {
		in, out := &in.TopologicalOrder, &out.TopologicalOrder
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(apiv1alpha1.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]apiv1alpha1.ResourceInformation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphRevisionStatus.
func (in *GraphRevisionStatus) DeepCopy() *GraphRevisionStatus {
	if in == nil {
		return nil
	}
	out := new(GraphRevisionStatus)
	in.DeepCopyInto(out)
	return out
}
