variants:
- name: kro-core-install-manifests
  values:
    rbac:
      mode: aggregation
- name: kro-core-install-manifests-with-prometheus
  values:
    rbac:
      mode: aggregation
    metrics:
      service:
        create: true
      serviceMonitor:
        enabled: true
- name: kro-core-install-manifests-with-pprof
  values:
    rbac:
      mode: aggregation
    debug:
      pprof:
        enabled: true
        service:
          enabled: true
