// Copyright 2025 The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package metrics

import "github.com/prometheus/client_golang/prometheus"

var (
	NodeEvalTotal = prometheus.NewCounter(
		prometheus.CounterOpts{
			Name: "runtime_node_eval_total",
			Help: "Total number of node evaluations during reconciliation",
		},
	)

	NodeEvalDuration = prometheus.NewHistogram(
		prometheus.HistogramOpts{
			Name:    "runtime_node_eval_duration_seconds",
			Help:    "Duration of node evaluations during reconciliation in seconds",
			Buckets: prometheus.DefBuckets,
		},
	)

	NodeEvalErrorsTotal = prometheus.NewCounter(
		prometheus.CounterOpts{
			Name: "runtime_node_eval_errors_total",
			Help: "Total number of node evaluation errors",
		},
	)

	RuntimeCreationTotal = prometheus.NewCounter(
		prometheus.CounterOpts{
			Name: "runtime_creation_total",
			Help: "Total number of runtimes created",
		},
	)

	RuntimeCreationDuration = prometheus.NewHistogram(
		prometheus.HistogramOpts{
			Name:    "runtime_creation_duration_seconds",
			Help:    "Duration of runtime creation setup phase in seconds",
			Buckets: prometheus.DefBuckets,
		},
	)

	NodeIgnoredCheckTotal = prometheus.NewCounter(
		prometheus.CounterOpts{
			Name: "runtime_node_ignored_check_total",
			Help: "Total number of node includeWhen checks",
		},
	)

	NodeIgnoredTotal = prometheus.NewCounter(
		prometheus.CounterOpts{
			Name: "runtime_node_ignored_total",
			Help: "Total number of nodes skipped due to includeWhen conditions",
		},
	)

	NodeReadyCheckTotal = prometheus.NewCounter(
		prometheus.CounterOpts{
			Name: "runtime_node_ready_check_total",
			Help: "Total number of node readyWhen checks",
		},
	)

	NodeNotReadyTotal = prometheus.NewCounter(
		prometheus.CounterOpts{
			Name: "runtime_node_not_ready_total",
			Help: "Total number of times nodes were not ready and blocked reconciliation",
		},
	)

	CollectionSize = prometheus.NewHistogram(
		prometheus.HistogramOpts{
			Name:    "runtime_collection_size",
			Help:    "Number of items generated by forEach collection expansion",
			Buckets: prometheus.ExponentialBuckets(1, 2, 10),
		},
	)
)
