name: Deploy docs

permissions:
  contents: read
  issues: read
  pull-requests: read

on:
  push:
    branches:
      - main
    paths:
      - "website/**"
      - "tools/krep-crawl/**"
      - ".github/workflows/deploy-docs.yaml"

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./website
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0

      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version: 20

      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6
        with:
          go-version-file: ./tools/krep-crawl/go.mod

      - name: Generate roadmap data
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: go run .
        working-directory: ./tools/krep-crawl

      - name: Install dependencies
        run: npm install --frozen-lockfile

      - name: Build website
        run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: ./website/build

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    defaults:
      run:
        working-directory: ./website
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
