name: 'Tag Release'

on:
  push:
    branches:
      - master
      - 'release-*'
    paths:
      - version.go

jobs:
  tag-release:
    if: ${{ github.repository == 'kubernetes-sigs/kro' }}
    runs-on: ubuntu-24.04

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5
      - run: /usr/bin/git config --global user.email actions@github.com
      - run: /usr/bin/git config --global user.name 'GitHub Actions Release Tagger'
      - run: dev/tasks/push-tag
