name: unit tests
on:
  push:
    branches: [ main ]
    paths:
      - "**.go"
      - go.mod
      - go.sum
      - scripts/ci/**
  pull_request:
    branches: [ main ]
    paths:
      - "**.go"
      - go.mod
      - go.sum
      - scripts/ci/**

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.24' ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run scripts/ci/presubmits/unit-tests
        run: scripts/ci/presubmits/unit-tests
