apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: dogsvscats-app.kro.run
spec:
  schema:
    apiVersion: v1alpha1
    kind: DogsvsCatsApp
    additionalPrinterColumns:
    - name: STATE
      type: string
      jsonPath: .status.state
    - name: SYNCED
      type: boolean
      jsonPath: .status.synced
    - name: AGE
      type: date
      jsonPath: .metadata.creationTimestamp
    - name: VOTE URL
      type: string
      jsonPath: .status.voteURL
    - name: RESULT URL
      type: string
      jsonPath: .status.resultURL
    spec:
      name: string
      namespace: string | default="default"
      # Infrastructure Configuration
      vpcID: string
      subnetIDs: "[]string"
      postgresEngineVersion: string | default="16.10"
      # Application Configuration
      voteImage: string | default="dogsvscats/vote:latest"
      resultImage: string | default="dogsvscats/result:latest"
      workerImage: string | default="dogsvscats/worker:latest"
      voteReplicas: integer | default=2
      resultReplicas: integer | default=1
      workerReplicas: integer | default=1
    status:
      voteReplicas: ${voteapp.status.availableReplicas}
      resultReplicas: ${resultapp.status.availableReplicas}
      workerReplicas: ${workerapp.status.availableReplicas}
      postgresEndpoint: ${postgres.status.endpoint}
      redisEndpoint: ${redis.status.endpoint}
      voteURL: ${voteapp.status.url}
      resultURL: ${resultapp.status.url}

  resources:
  # --- PostgreSQL Database ---
  - id: postgres
    readyWhen:
      - ${has(postgres.status.endpoint)}
    template:
      apiVersion: kro.run/v1alpha1
      kind: RDSPostgres
      metadata:
        name: ${schema.spec.name}-postgres
        namespace: ${schema.spec.namespace}
      spec:
        name: ${schema.spec.name}
        namespace: ${schema.spec.namespace}
        vpcID: ${schema.spec.vpcID}
        subnetIDs: ${schema.spec.subnetIDs}
        instanceClass: "db.t4g.micro"
        allocatedStorage: 20
        engineVersion: ${schema.spec.postgresEngineVersion}
        dbName: "postgres"
        masterUsername: "postgres"

  # --- Redis Cache ---
  - id: redis
    readyWhen:
      - ${has(redis.status.endpoint)}
    template:
      apiVersion: kro.run/v1alpha1
      kind: ElastiCacheServerless
      metadata:
        name: ${schema.spec.name}-redis
        namespace: ${schema.spec.namespace}
      spec:
        name: ${schema.spec.name}
        namespace: ${schema.spec.namespace}
        vpcID: ${schema.spec.vpcID}
        subnetIDs: ${schema.spec.subnetIDs}
        engine: "redis"
        dataStorageLimit: 1
        ecpuLimit: 1000
        description: "Redis cache for voting app"

  # --- Vote Application ---
  - id: voteapp
    readyWhen:
      - ${has(voteapp.status.availableReplicas)}
      - ${voteapp.status.availableReplicas > 0}
    template:
      apiVersion: kro.run/v1alpha1
      kind: VoteApp
      metadata:
        name: ${schema.spec.name}-vote-app
        namespace: ${schema.spec.namespace}
      spec:
        name: ${schema.spec.name}
        namespace: ${schema.spec.namespace}
        image: ${schema.spec.voteImage}
        replicas: ${schema.spec.voteReplicas}
        redisEndpoint: ${redis.status.endpoint}
        service:
          enabled: true
        ingress:
          enabled: true

  # --- Result Application ---
  - id: resultapp
    readyWhen:
      - ${has(resultapp.status.availableReplicas)}
      - ${resultapp.status.availableReplicas > 0}
    template:
      apiVersion: kro.run/v1alpha1
      kind: ResultApp
      metadata:
        name: ${schema.spec.name}-result-app
        namespace: ${schema.spec.namespace}
      spec:
        name: ${schema.spec.name}
        namespace: ${schema.spec.namespace}
        image: ${schema.spec.resultImage}
        replicas: ${schema.spec.resultReplicas}
        postgresEndpoint: ${postgres.status.endpoint}
        postgresSecretName: ${postgres.status.secretName}
        service:
          enabled: true
        ingress:
          enabled: true

  # --- Worker Application ---
  - id: workerapp
    readyWhen:
      - ${has(workerapp.status.availableReplicas)}
      - ${workerapp.status.availableReplicas > 0}
    template:
      apiVersion: kro.run/v1alpha1
      kind: WorkerApp
      metadata:
        name: ${schema.spec.name}-worker-app
        namespace: ${schema.spec.namespace}
      spec:
        name: ${schema.spec.name}
        namespace: ${schema.spec.namespace}
        image: ${schema.spec.workerImage}
        replicas: ${schema.spec.workerReplicas}
        redisEndpoint: ${redis.status.endpoint}
        postgresEndpoint: ${postgres.status.endpoint}
        postgresSecretName: ${postgres.status.secretName}
