apiVersion: kro.run/v1alpha1
kind: DogsvsCatsApp
metadata:
  name: dogsvscats-voting-app
  namespace: default
spec:
  name: dogsvscats-voting-app
  namespace: default
  # Infrastructure values for ap-southeast-2 region
  vpcID: "vpc-0087753f93a7a32e6"
  subnetIDs: ["subnet-028d4ae9e26605ab2", "subnet-094c0ebceba967f5f", "subnet-07afde0cb81ba4c2e"]
  postgresEngineVersion: "16.10"
  # Application configuration
  voteImage: "dogsvscats/vote:latest"
  resultImage: "dogsvscats/result:latest"
  workerImage: "dogsvscats/worker:latest"
  voteReplicas: 2
  resultReplicas: 1
  workerReplicas: 1